fra = input("Digite seu nome completo; ")
contar= len(fra)
maius = fra.upper()
print("Seu nome com todas as letras em maiuscula;  " + maius)
minus = fra.lower()
print("Seu nome com todas as letras em minuscula;  " + minus)
semespaço = fra.strip()
print(f'Seu nome com os espaços tem{contar} e esse é sem os espaços {len(semespaço)-fra.count(' ')}')
nameprin = fra.split(' ')
print(f'Seu nome principal tem {len(nameprin[0])}  caractere')
